# .travis.yml     Travis CI configuration file for HSTR
#
# Copyright (C) 2014-2020  Martin Dvorak <martin.dvorak@mindforger.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

os:
  - linux

language: c
compiler:
  - gcc

services:
  - xvfb

addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntu-sdk-team/ppa'
    packages:
      - qttools5-dev-tools
      - ccache
      - automake
      - gcc
      - make
      - libncursesw5-dev
      - libreadline-dev

matrix:
  include:
    - os: linux
      dist: trusty

before_install:
  - eval "${MATRIX_EVAL}"

install:
  - "export DISPLAY=:99.0"
  - "export HSTRHOME=`pwd`"

script:
  - echo "1) make hstr"
  - cd "${HSTRHOME}"
  - cd build/tarball && ./tarball-automake.sh
  - cd "${HSTRHOME}"
  - ./configure && make
  - cd src && ./hstr --version
  - echo "2) run unit tests"
  - cd "${HSTRHOME}"
  - cd build && ./test-units.sh
